"""initial

Revision ID: 353200b6d12f
Revises: 
Create Date: 2025-04-19 11:46:13.789060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '353200b6d12f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Tabla de usuarios
    op.create_table('user',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('username', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=True),
        sa.Column('full_name', sa.String(length=255), nullable=True),
        sa.Column('role', sa.String(length=50), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_verified', sa.Boolean(), nullable=True),
        sa.Column('preferences', sa.JSON(), nullable=True),
        sa.Column('settings', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
    
    # Tabla de ingredientes
    op.create_table('ingredient',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('protein', sa.Float(), nullable=True),
        sa.Column('fat', sa.Float(), nullable=True),
        sa.Column('carbohydrates', sa.Float(), nullable=True),
        sa.Column('fiber', sa.Float(), nullable=True),
        sa.Column('calories', sa.Float(), nullable=True),
        sa.Column('allergens', sa.JSON(), nullable=True),
        sa.Column('origin', sa.String(length=100), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredient_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredient_name'), ['name'], unique=False)
    
    # Tabla de proveedores
    op.create_table('supplier',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('contact_name', sa.String(length=255), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('supplier_type', sa.String(length=50), nullable=True),
        sa.Column('payment_terms', sa.String(length=255), nullable=True),
        sa.Column('delivery_time', sa.Integer(), nullable=True),
        sa.Column('minimum_order', sa.String(length=255), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('rating', sa.Integer(), nullable=True),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_name'), ['name'], unique=False)
    
    # Tabla de recetas
    op.create_table('recipe',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('version', sa.String(length=10), nullable=True),
        sa.Column('is_public', sa.Boolean(), nullable=True),
        sa.Column('dough_hydration', sa.Float(), nullable=True),
        sa.Column('dough_weight', sa.Integer(), nullable=True),
        sa.Column('dough_temp', sa.Float(), nullable=True),
        sa.Column('cooking_temp', sa.Integer(), nullable=True),
        sa.Column('preparation_time', sa.Integer(), nullable=True),
        sa.Column('fermentation_time', sa.Integer(), nullable=True),
        sa.Column('cooking_time', sa.Integer(), nullable=True),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('source', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_name'), ['name'], unique=False)
    
    # Tabla de relación entre ingredientes y recetas
    op.create_table('recipeingredient',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('recipe_id', sa.String(length=36), nullable=False),
        sa.Column('ingredient_id', sa.String(length=36), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('unit', sa.String(length=20), nullable=False),
        sa.Column('order', sa.Integer(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('is_optional', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
        sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Tabla de pasos de recetas
    op.create_table('recipestep',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('recipe_id', sa.String(length=36), nullable=False),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('time', sa.Integer(), nullable=True),
        sa.Column('temperature', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Tabla de fichas técnicas de recetas
    op.create_table('recipesheet',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('recipe_id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('version', sa.String(length=10), nullable=True),
        sa.Column('revision_number', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('target_market', sa.String(length=255), nullable=True),
        sa.Column('certification', sa.JSON(), nullable=True),
        sa.Column('serving_size', sa.String(length=100), nullable=True),
        sa.Column('yield_amount', sa.Float(), nullable=True),
        sa.Column('yield_unit', sa.String(length=20), nullable=True),
        sa.Column('shelf_life_ambient', sa.String(length=50), nullable=True),
        sa.Column('shelf_life_refrigerated', sa.String(length=50), nullable=True),
        sa.Column('shelf_life_frozen', sa.String(length=50), nullable=True),
        sa.Column('quality_parameters', sa.JSON(), nullable=True),
        sa.Column('critical_control_points', sa.JSON(), nullable=True),
        sa.Column('packaging_info', sa.JSON(), nullable=True),
        sa.Column('storage_info', sa.JSON(), nullable=True),
        sa.Column('nutrition', sa.JSON(), nullable=True),
        sa.Column('allergens', sa.JSON(), nullable=True),
        sa.Column('approved_by', sa.String(length=255), nullable=True),
        sa.Column('approval_date', sa.Date(), nullable=True),
        sa.Column('author', sa.String(length=255), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipesheet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipesheet_name'), ['name'], unique=False)
    
    # Tabla de precios de ingredientes
    op.create_table('ingredientprice',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('ingredient_id', sa.String(length=36), nullable=False),
        sa.Column('supplier_id', sa.String(length=36), nullable=True),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('unit', sa.String(length=20), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=False),
        sa.Column('is_current', sa.Boolean(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('source', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
        sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredientprice')
    
    with op.batch_alter_table('recipesheet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipesheet_name'))
    op.drop_table('recipesheet')
    
    op.drop_table('recipestep')
    op.drop_table('recipeingredient')
    
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_name'))
        batch_op.drop_index(batch_op.f('ix_recipe_category'))
    op.drop_table('recipe')
    
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_name'))
    op.drop_table('supplier')
    
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_name'))
        batch_op.drop_index(batch_op.f('ix_ingredient_category'))
    op.drop_table('ingredient')
    
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
    op.drop_table('user')
    # ### end Alembic commands ###
